-- AlterTable
ALTER TABLE "User" ALTER COLUMN "progOne" SET DEFAULT E'#E47A77',
ALTER COLUMN "progFive" SET DEFAULT E'#E47A77',
ALTER COLUMN "progFour" SET DEFAULT E'#E47A77',
ALTER COLUMN "progThree" SET DEFAULT E'#E47A77',
ALTER COLUMN "progTwo" SET DEFAULT E'#E47A77';
